"""Framework-agnostic CSS variable adapter — Phase 10B.

Outputs (PLUGIN_PLAN §7.1/§7.2):
    design-system/tokens.css         — managed block: :root + [data-theme='dark']
                                       + prefers-color-scheme fallback
    design-system/fonts.css          — (ko locale) Pretendard @font-face + --ds-font-ko
    design-system/fonts/...          — (ko) Pretendard placeholder + LICENSE-FONTS
                                       + fetch-pretendard.mjs (TARGET rewritten for
                                       design-system/fonts/)
    design-system/README.md          — 2-3줄 수동 통합 스니펫
    design-system/<preset mirror>    — shared mirror ops (manifest, system_spec, ...)

Merge rules (§7.4):
    * design-system/tokens.css  → managed-block replace; markers 없으면 .ds-proposed
    * design-system/fonts.css   → 동일 정책
    * design-system/** 기타     → generator-owned → overwrite
    * 그 외 모든 경로           → .ds-proposed (raw 어댑터는 repo 루트를 건드리지 않음)
"""

from __future__ import annotations

from pathlib import Path

from .base import (
    DS_BLOCK_END,
    DS_BLOCK_START,
    FileOp,
    LocalePairing,
    PresetBundle,
    StackAdapter,
    css_var_declarations,
    design_system_mirror_ops,
    pretendard_asset_ops,
    replace_managed_block,
    resolve_locale_pairing,
    tokens_for_mode,
    wrap_managed_css,
)
from ..token_emitter import reading_rhythm_declarations


ADAPTER_ID = "raw-css-variables"
ADAPTER_VERSION = "0.1.0"
SUPPORTED_PRESET_API = ">=1.0.0 <2.0.0"


# ---------------------------------------------------------------------------
# File builders


def _build_tokens_css(
    bundle: PresetBundle,
    color_modes: list[str],
    *,
    korean_locale: bool = False,
) -> str:
    lines: list[str] = []
    lines.append(
        f"/* preset: {bundle.id} — generated by {ADAPTER_ID}@{ADAPTER_VERSION} */"
    )

    light_tokens = tokens_for_mode(bundle, "light")
    lines.append("")
    lines.append(":root {")
    lines.extend(css_var_declarations(light_tokens))
    lines.append("  --ds-radius-sm: 4px;")
    lines.append("  --ds-radius-md: 8px;")
    lines.append("  --ds-radius-lg: 12px;")
    # 조판 계약도 토큰으로 나가야 한다. 색만 방출하면 preset으로 설치한 프로젝트는
    # 본문 행간·자간·줄바꿈을 바인딩할 대상이 없어서 숫자를 직접 쓰게 된다.
    lines.extend(
        reading_rhythm_declarations(bundle.font_system, korean_locale=korean_locale)
    )
    lines.append("}")

    if "dark" in color_modes:
        dark_tokens = tokens_for_mode(bundle, "dark")
        lines.append("")
        lines.append("[data-theme='dark'] {")
        lines.extend(css_var_declarations(dark_tokens))
        lines.append("}")

        lines.append("")
        lines.append("@media (prefers-color-scheme: dark) {")
        lines.append("  :root:not([data-theme='light']) {")
        for decl in css_var_declarations(dark_tokens):
            lines.append("  " + decl)
        lines.append("  }")
        lines.append("}")

    return wrap_managed_css("\n".join(lines))


def _build_fonts_css(pairing: LocalePairing) -> str:
    # Fonts live next to fonts.css in design-system/fonts/.
    body = (
        f"/* locale: {pairing.locale} — Pretendard pairing */\n"
        "@font-face {\n"
        '  font-family: "Pretendard Variable";\n'
        "  font-style: normal;\n"
        "  font-weight: 45 920;\n"
        "  font-display: swap;\n"
        '  src: url("./fonts/PretendardVariable.woff2") format("woff2-variations");\n'
        "}\n"
        "\n"
        ":root {\n"
        '  --ds-font-ko: "Pretendard Variable", "Pretendard", system-ui, -apple-system, sans-serif;\n'
        "  --ds-font-heading: var(--ds-font-ko);\n"
        "  --ds-font-body: var(--ds-font-ko);\n"
        f'  --ds-font-mono: "{pairing.mono_font or "IBM Plex Mono"}", ui-monospace, SFMono-Regular, Menlo, monospace;\n'
        "}\n"
        "\n"
        "html[lang='ko'], [data-locale='ko'] {\n"
        "  font-family: var(--ds-font-ko);\n"
        "}"
    )
    return wrap_managed_css(body)


def _build_readme(preset_id: str, has_fonts_css: bool) -> str:
    link_lines = ['<link rel="stylesheet" href="./design-system/tokens.css" />']
    if has_fonts_css:
        link_lines.append('<link rel="stylesheet" href="./design-system/fonts.css" />')
    link_block = "\n".join(link_lines)

    return (
        f"# design-system ({preset_id})\n"
        "\n"
        f"Generated by `{ADAPTER_ID}@{ADAPTER_VERSION}`.\n"
        "\n"
        "## 수동 통합\n"
        "\n"
        "HTML `<head>` 에 아래 스니펫을 추가하세요.\n"
        "\n"
        "```html\n"
        f"{link_block}\n"
        "```\n"
        "\n"
        "- `tokens.css` — 색상/반경 CSS 변수 (`:root`, dark 지원 프리셋은 `[data-theme='dark']` + `@media (prefers-color-scheme: dark)`)\n"
        + ("- `fonts.css` — Pretendard `@font-face` 및 `--ds-font-ko` (ko 로케일)\n" if has_fonts_css else "")
        + "- `STYLE.md` / `DESIGN.md` — 에이전트가 먼저 읽는 스타일 캡슐\n"
        + "- 나머지 파일 — 프리셋 산출물 (직접 수정하지 말고 재설치로 갱신)\n"
        "\n"
        "예시: `color: var(--ds-color-ink); background: var(--ds-color-surface);`\n"
    )


# ---------------------------------------------------------------------------
# Adapter class


class RawCssVariablesAdapter(StackAdapter):
    id: str = ADAPTER_ID
    version: str = ADAPTER_VERSION
    supported_preset_api: str = SUPPORTED_PRESET_API

    def detect(self, target_repo: Path) -> float:
        score = 0.5
        pkg = target_repo / "package.json"
        if not pkg.exists():
            score = 0.6

        has_tailwind = any(
            (target_repo / f"tailwind.config.{ext}").exists()
            for ext in ("ts", "mts", "cts", "js", "mjs", "cjs")
        )
        has_components_json = (target_repo / "components.json").exists()
        if not has_tailwind and not has_components_json:
            score += 0.1

        return round(min(score, 1.0), 3)

    def render(
        self,
        preset: PresetBundle,
        target_repo: Path,
        color_mode: str,
        locale: str = "en",
    ) -> list[FileOp]:
        supported_modes = preset.color_modes or [preset.default_color_mode]
        if color_mode not in supported_modes:
            raise ValueError(
                f"preset {preset.id} does not support color_mode='{color_mode}' "
                f"(supported: {supported_modes})"
            )

        pairing = resolve_locale_pairing(preset, locale) if locale != "en" else None
        has_fonts_css = locale == "ko" and pairing is not None

        ops: list[FileOp] = []
        ops.append(
            FileOp(
                path="design-system/tokens.css",
                content=_build_tokens_css(
                    preset, supported_modes, korean_locale=locale == "ko"
                ),
                action="create",
            )
        )

        if has_fonts_css:
            ops.append(
                FileOp(
                    path="design-system/fonts.css",
                    content=_build_fonts_css(pairing),
                    action="create",
                )
            )
            ops.extend(
                pretendard_asset_ops(
                    assets_dir="design-system/fonts",
                    fetch_script_path="design-system/fonts/fetch-pretendard.mjs",
                )
            )

        ops.append(
            FileOp(
                path="design-system/README.md",
                content=_build_readme(preset.id, has_fonts_css),
                action="create",
            )
        )

        ops.extend(design_system_mirror_ops(preset))

        return ops

    def merge(self, op: FileOp, existing_path: Path) -> FileOp:
        path = op.path
        try:
            existing = existing_path.read_text(encoding="utf-8")
        except (FileNotFoundError, UnicodeDecodeError):
            return FileOp(
                path=f"{path}.ds-proposed",
                content=op.content,
                action="proposed",
                reason="unreadable existing file",
                original_path=path,
            )

        if path in ("design-system/tokens.css", "design-system/fonts.css"):
            if DS_BLOCK_START not in existing or DS_BLOCK_END not in existing:
                return FileOp(
                    path=f"{path}.ds-proposed",
                    content=op.content,
                    action="proposed",
                    reason=f"existing {path} has no design-ontology managed block",
                    original_path=path,
                )
            start = op.content.find(DS_BLOCK_START)
            end = op.content.find(DS_BLOCK_END)
            if start == -1 or end == -1:
                return FileOp(
                    path=f"{path}.ds-proposed",
                    content=op.content,
                    action="proposed",
                    reason="generated block markers missing",
                    original_path=path,
                )
            new_body = op.content[start + len(DS_BLOCK_START) : end].strip()
            updated, _ = replace_managed_block(existing, new_body)
            return FileOp(path=path, content=updated, action="merge")

        # design-system/ 나머지는 generator-owned → overwrite.
        if path.startswith("design-system/"):
            return FileOp(path=path, content=op.content, action="overwrite")

        # Raw 어댑터는 user repo 최상위를 건드리지 않음.
        return FileOp(
            path=f"{path}.ds-proposed",
            content=op.content,
            action="proposed",
            reason="raw-css-variables does not modify files outside design-system/",
            original_path=path,
        )
